version: "3"

services:
  tananthanh:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: tananthanh
    working_dir: /var/www/html
    ports:
      - "9000:80"
    volumes:
        - .:/var/www/html
        - ./docker/nginx_log:/var/log/nginx
        - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
        - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf

  mysql_db:
    image: mysql:latest
    container_name: tananthanh_mysql
    ports:
    - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tananthanh
  
  phpmyadmin:
    container_name: tananthanh_phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "9999:80"
    environment:
      PMA_ARBITRARY: 1

